version: '3.8'

services:

  fastapi:
    build: .
    ports:
      - "80:80"
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    container_name: fastapi
    environment:
      access_token: ${access_token}
      bot_id: ${bot_id}


  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
